joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 10.0
      y: 10.0
    scale_linear_turbo:
      x: 8.0
      y: 8.0
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 10.0
    scale_angular_turbo:
      yaw: 6.0


    enable_button: 5
    enable_turbo_button: 6

    require_enable_button: true
